### ISSUE TITLE
Says "Linux" but doesn't work on CentOS 7

### ISSUE THREAD

**Issue by utdrmac** [Sjakil/gunthy-gui#1]
Can you please provide a more generic "linux" version that runs on all major flavors? Right now, CentOS Linux release 7.3.1611 (Core) is the latest and it only supports up to GLIBCXX_3.4.19.

3.4.20 is simply not available for CentOS 7. Asking people to run a different OS is out of the question.

Would love to use this but need a version that is more generic for non-bleeding-edge operating systems.

**Comment by Sjakil** [comment]
That's fair point, it should work on all distros of linux. The problem I'm facing is that the GUI is built using NodeJS and I need to compile it to an executable. There are only a number of options when it comes to compiling NodeJS scripts this way. I'm currently using [node-compiler](https://github.com/pmq20/node-compiler), as this was the only reliable way I found after some research. Because of this I'm pretty limited when it comes to compilation options and libraries that are used. There might be better options, I'm open to suggestions. 

Some time ago, a user of the GUI posted his solution to the problem. You can find it [here](https://github.com/Sjakil/gunthy-gui/wiki/Common-Errors#libstdcso6-version-glibcxx_3420-not-found-required-by-gunthy-gui-linux-x64). If for some reason this doesn't work please let me know.

**Comment by utdrmac** [comment]
Looking at node-compiler's requirements, says gcc 4.8.2 (or better). CentOS 7 offers up 4.8.5. clang 3.4 (or better). CentOS 7 offers up 3.4.2.

So, seems that if you ran node-compiler on CentOS 7 box, you'd be able to compile for CentOS 7 without needing some experimental libc versions that are only supported on the most critically-bleeding-edge versions.

**Comment by utdrmac** [comment]
I read the "work around" and asking people to recompile gcc is out of the question except for the most seasoned of developers. That is not an appropriate work-around for average-joe-user.

**Comment by Sjakil** [comment]
Another fair point. I set up a Cent OS 7 machine and compiled it on there. It was just in time for version 0.95. In my tests the GUI ran on this same machine without needing GLIBCXX 3.4.20 anymore. Also still worked on my other machines (Ubuntu 14.04).

**Comment by utdrmac** [comment]
Excellent. I look forward to testing out your CentOS7 version.
