### ISSUE TITLE
0.96 / 0.97 - UI crash on return to browser focus

### ISSUE THREAD

**Issue by CultureCrypto** [Sjakil/gunthy-gui#8]
If I leave the window in focus, everything seems to work ok, but if I switch to a different tab (Chrome - Version 60.0.3112.101 (Official Build) (64-bit)), or a different program, then return - the UI hangs, stating with "The GUI server has shut down, please restart it, then refresh" (but the server hasn't shut down - it's running).

Is there a practical limit to the number of currency pairs supported?  Maybe # of pairs per unit of RAM?  Just free-wheeling here...

**Comment by Sjakil** [comment]
Hey Culture! 

The drop in performance and inevitable disconnect happened because the GUI handled the log output of gunbot in an inefficient way. Version 0.98 should take care of this issue. Could you please check if it works better for you now?

There must be a limit somewhere, but it shouldn't be easily reached on a modern PC (unless code is not optimized).

**Comment by CultureCrypto** [comment]
Latest (0.98) is working well with no connection drops so far... I will continue to watch!  Thanks!
